[workspace]
members = [
    "crates/holochain-conductor-runtime",
    "crates/holochain-conductor-runtime-ffi",
    "crates/tauri-plugin-holochain-service",
    "crates/tauri-plugin-holochain-service-consumer",
    "apps/android-service-runtime/src-tauri",
    "examples/service-app/src-tauri",
]
resolver = "2"

[workspace.dependencies]
holochain_runtime = { git = "https://github.com/mattyg/p2p-shipyard", branch = "feat/foreground-service", default-features = false }
holochain = "0.4.1"
holochain_conductor_api = "0.4.1"
holochain_types = "0.4.1"
kitsune_p2p_types = "0.4.1"
sodoken = "0.0.11"
url2 = "0.0.6"

tauri = "2.2.5"
tauri-plugin = "2.0.4"
tauri-build = { version = "2.0.5", default-features = false }

log = "0.4.25"
android_logger = "0.14.1"
serde = "1.0"
thiserror = "2.0.11"
bytes = "1.9.0"
zeroize = "1.8.1"
uniffi = "0.28.1"
tempfile = "3.17.1"
tokio = "1.43.0"
uuid = "1.15.1"
