[workspace]
members = ["apps/android-service-runtime/src-tauri", "crates/**"]
resolver = "2"

[workspace.dependencies]
tauri = "2.2.5"
tauri-plugin = "2.0.4"
tauri-build = "2.0.5"

holochain_conductor_api = "0.4.1"
holochain_types = "0.4.1"

url2 = "0.0.6"
log = "0.4.25"
android_logger = "0.14.1"

serde = "1.0.217"
thiserror = "2.0.11"
bytes = "1.9.0"
uniffi = "0.28.1"
