packages:
  - crates/tauri-plugin-holochain-service
  - crates/tauri-plugin-holochain-service-consumer
  - apps/android-service-runtime
  - '!**/android/**'
  - '!**/dist-js/**'
  - '!**/permissions/**'