name: Build Apps

on:
  pull_request:
    branches:
      - main
      - main-*

jobs:
  build-apps:
    name: Build apps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - android-service-runtime
          - example-client-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: false
          swap-storage: false
        
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Build app ${{ matrix.name }}
        run: |
          nix develop --no-update-lock-file --command bash -c "pnpm install && pnpm run build:${{ matrix.name }} --target x86_64 --apk"

  build-tauri-plugins:
    name: Build tauri-plugins
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - tauri-plugin-service
          - tauri-plugin-client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: false
          swap-storage: false
        
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Build tauri plugin ${{ matrix.name }}
        run: |
          nix develop --no-update-lock-file --command bash -c "pnpm install && pnpm run build:${{ matrix.name }}"