name: "release-library-client"
on:
  push:
    tags:
      - 'client-v[0-9]+.[0-9]+.[0-9]+'
      - 'client-v[0-9]+.[0-9]+.[0-9]+-[a-z]+'
      - 'client-v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'

jobs:
  release:
    permissions: write-all
    environment: Maven Central Release
    runs-on: 'ubuntu-22.04' 
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: false

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci
                
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Generate gradle.properties
        run: |
          cp libraries/client/gradle.properties.ci libraries/client/gradle.properties

          base64 -d <<< "${{ secrets.SIGNING_KEY_RING_FILE_B64 }}" >> $RUNNER_TEMP/keyring.gpg
          echo "signing.secretKeyRingFile=$RUNNER_TEMP/keyring.gpg" >> libraries/client/gradle.properties
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> libraries/client/gradle.properties
          echo "signing.password=${{ secrets.SIGNING_KEY_PASSWORD }}" >> libraries/client/gradle.properties
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> libraries/client/gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> libraries/client/gradle.properties

      - name: Build
        run: |
          nix develop --no-update-lock-file --command bash -c "pnpm install && pnpm run build-all:client"

      - name: Publish to Maven Central
        run: |
          nix develop --no-update-lock-file --command bash -c "cd libraries/client && ./gradlew publish"
