name: "release-library-service"
on:
  push:
    tags:
      - 'service-v[0-9]+.[0-9]+.[0-9]+'
      - 'service-v[0-9]+.[0-9]+.[0-9]+-[a-z]+'
      - 'service-v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'

jobs:
  release:
    permissions: write-all
    environment: Maven Central Release
    runs-on: 'ubuntu-22.04' 
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: false

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci
                
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cp libraries/service/gradle.properties.ci libraries/service/gradle.properties
          nix develop --no-update-lock-file --command bash -c "pnpm install && pnpm run build-all:service"

      - name: Publish to Maven Central
        run: |
          nix develop --no-update-lock-file --command bash -c "pnpm run publish:service"
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }} 
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }} 
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}