name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-rust-crates:
    name: Test Rust Crates
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
        ]
        toolchain: [
          "1.81.0", # Check the version used by Holochain
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Make Test
        run: make test

  test-kotlin-libraries:
    name: Test Kotlin Libraries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        android-api-level: [
          27,
        ]
        arch: [
          x86_64,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'gradle'
        
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api-level }}
          target: google_apis
          arch: ${{ matrix.arch }}
          script: cd libraries/holochain-service-client && ./gradlew connectedDebugAndroidTest