name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-rust-crates:
    name: Test Rust Crates
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
        ]
        toolchain: [
          "1.81.0", # Check the version used by Holochain
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Make Test
        run: make test

  test-kotlin-libraries:
    name: Test Kotlin Libraries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - api-level: 28
            arch: x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create gradle.properties without secrets
        run: |
          ls -la
          touch android-service-runtime/libraries/android-service-client/gradle.properties
          echo "android.enableJetifier=true\nandroid.useAndroidX=true" > android-service-runtime/libraries/android-service-client/gradle.properties

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.target.api-level }}-${{ matrix.target.arch }}

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.target.api-level }}
          arch: ${{ matrix.target.arch }}
          target: google_apis
          script: cd libraries/holochain-service-client && ./gradlew connectedDebugAndroidTest